apiVersion: apps/v1
kind: Deployment
metadata:
    name: react-activity
    namespace: MPGENV
spec:
   replicas: 1
   selector:
      matchLabels:
         app: react-activity
   template:
     metadata:
        labels:
          app: react-activity
          release: MPGRELEASE.MPGENV.MPGBUILD_NUMBER
     spec:
        containers:
        - name: react-activity
          image: mpastorg/react-activity:MPGRELEASE.MPGENV.MPGBUILD_NUMBER
          imagePullPolicy: Always
          ports:
          - containerPort: 443
            containerPort: 80
            containerPort: 8079
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 50m
              memory: 512Mi
        nodeSelector:
          kubernetes.io/arch: amd64