pipeline {
  agent any
  environment {
    ENV = 'pro'
    MPGHTTP_PORT = 32215
    RELEASE = '0.1'
    registry = "mpastorg/react-activity"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  stages {
    stage('prepare for kubernetes') {
      steps{
        sh "sed 's/MPGRELEASE.MPGBUILD_NUMBER/$RELEASE.$BUILD_NUMBER/' react-deplo.yml > deplo_1.yml"
        sh "sed 's/MPGENV/default/' deplo_1.yml > deplo_1b.yml"
      }
    }
    stage('SSH Into k8s Server') {
      steps{
        script{
            def remote = [:]
            remote.name = 'mpg4ras01'
            remote.host = 'mpg4ras01'
            remote.allowAnyHosts = true
            withCredentials([usernamePassword(credentialsId: 'mpgubumac01', usernameVariable: 'USERNAME'
            , passwordVariable: 'PASSWORD')])
            {
                remote.user = "$USERNAME"
                remote.password = "$PASSWORD"
                sshPut remote: remote, from: 'deplo_1b.yml', into: '.'
                sshCommand remote: remote, command: "kubectl apply -f deplo_1b.yml"
                sshRemove remote: remote, path: 'deplo_1b.yml'
            }
        }
      }
    }
  }
}